
import type { Metadata } from 'next'
import './globals.css'
import Header from './components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={false ? "dark" : "light"}>
      <body className="dark:bg-slate-900 dark:text-white">
        <Header />
        {children}</body>
    </html>
  )
}
